services:
  postgres:
    image: postgres:17
    container_name: game-library-db

    environment:
      POSTGRES_USER: gamelibrary
      POSTGRES_PASSWORD: gamelibrary
      POSTGRES_DB: gamelibrary

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
